spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Prajwal/Projects/Springboot e-Commerce/H2Database
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS
management.endpoint.shutdown.enabled=true
server.shutdown=GRACEFUL
management.info.env.enabled=true
info.app.name=e-comm
info.app.description=Spring Micro Arch & System Design
info.app.version=t0.01