spring.application.name=ecom-application
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Prajwal/Projects/Springboot e-Commerce/H2Database
spring.datasource.username=test
spring.datasource.password=test
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update